# Generated by Django 5.2.6 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=64)),
                ('join_time', models.CharField(max_length=128)),
            ],
        ),
    ]
