# Generated by Django 5.2.6 on 2025-10-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwdSaveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('pwd', models.CharField(max_length=128)),
            ],
        ),
    ]
