# Generated by Django 5.2.6 on 2025-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_web', '0002_pwdsaveinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='department',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='join_time',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
